@startuml
'https://plantuml.com/sequence-diagram


!include mat_mod.puml
!include material_db.puml
!include cross_section.puml
!include cs_model.puml
!include shear_zone.puml

package bmcs_design{
class Beam{
    stability()
    deflection()
}
class Anchorage{
    length()
    }
}

@enduml