@startuml
'https://plantuml.com/sequence-diagram


abstract class MatMod

package ConcreteMatMod{
class ConcreteMatMod
ConcreteMatMod --|> MatMod
ElasticConcreteMatMod --|> ConcreteMatMod
EC2ConcreteMatMod --|> ConcreteMatMod
PWLConcreteMatMod --|> ConcreteMatMod
}
package ReinfMatMod{
class ReinfMatMod
ReinfMatMod --|> MatMod
SteelMatMod --|> ReinfMatMod
CarbonMatMod --|> ReinfMatMod
}

package BondMatMod{
class BondMatMod
BondMatMod --|> MatMod
MultilinearBondMatMod --|> BondMatMod
DamageBondMatMod --|> BondMatMod
PlasticBondMatMod --|> BondMatMod
DamagePlasticBondMatMod --|> BondMatMod
}

package MaterialDB{
abstract class MaterialComponent

class ReinfMaterial

class ConcreteMixture
ConcreteMixture --|> MaterialComponent
ConcreteMatMod --o "1*" ConcreteMixture : < mat_mod

class ReinfMaterial
ReinfMaterial --|> MaterialComponent
ReinfMatMod --o "1*" ReinfMaterial : < mat_mod

class BondMaterial
BondMaterial --|> MaterialComponent
BondMaterial o--> ReinfMaterial
BondMaterial o--> ConcreteMixture

BondMatMod --o "1*" BondMaterial : < mat_mod
}

package CrossSection{
class CSDesign{
}

class CSShape{
}

class RectangularShape{
}

class TShape{
}

RectangularShape --|> CSShape
TShape --|> CSShape

class ReinfLayout{

}

ReinfLayout o--> Reinf

class Reinf{
 float position
}
class BarReinf{
}
class FabricReinf{
}

BarReinf --|> Reinf
FabricReinf --|> Reinf

CSDesign *--> CSShape
CSDesign *--> ReinfLayout

Reinf o--> ReinfMaterial: reinf_material >

CSDesign o--> ConcreteMixture : matrix_matmod
}

package bmcs_analysis{

class History{
}

class BMCSModel{
}

BMCSModel --> History

BMCSModel "1*" --> Load : loads >
BMCSModel "1*" --> Support : supports >

BMCSModel *--> CSDesign
abstract class BC{
}
class Support{
}
class Load{
}
Support --|> BC
Load --|> BC

class BMCSNModel{
}

class BMCSAModel{
}

BMCSNModel --|> BMCSModel
BMCSAModel --|> BMCSModel

class PullOutNModel
class PullOutAModel
class MKappaModel
class FragmentationModel
class BendingModel

PullOutNModel --|> BMCSNModel
PullOutAModel --|> BMCSAModel
CrackBridgeNModel --|> BMCSNModel
CrackBridgeAModel --|> BMCSAModel
MKappaModel --|> BMCSAModel
FragmentationModel --|> BMCSAModel
BendingModel --|> BMCSAModel
}

package bmcs_design{
class Beam{
    stability()
    deflection()
}
class Anchorage{
    length()
    }
}

@enduml